<?php

namespace Drupal\commerce_payment;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\commerce_payment\Event\FilterPaymentGatewaysEvent;
use Drupal\commerce_payment\Event\PaymentEvents;
use Drupal\commerce_payment\Plugin\Commerce\PaymentGateway\SupportsStoredPaymentMethodsInterface;
use Drupal\Component\Uuid\UuidInterface;
use Drupal\Core\Cache\MemoryCache\MemoryCacheInterface;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Config\Entity\ConfigEntityStorage;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Language\LanguageManagerInterface;
use Drupal\user\UserInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class PaymentGatewayStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\commerce_payment\PaymentGatewayStorageInterface
{
    public function loadForUser(UserInterface $account)
    {
        return $this->getOriginalObject()->loadForUser($account);
    }
    public function loadMultipleForOrder(OrderInterface $order)
    {
        return $this->getOriginalObject()->loadMultipleForOrder($order);
    }
}
