_core:
  default_config_hash: 5G059LQS_7DV7oGUpxVTPM0aWtunW7bvDpRkgeb0KtE
langcode: es
custom:
  activate: 0
  open_effect: zoom
  close_effect: zoom
  slide_effect: slide
  width: 98%
  height: 98%
  close_on_outside_click: true
  more_text: 'See more'
  more_length: 60
  desc_position: bottom
  loop: false
  zoomable: true
  draggable: true
  preload: true
  autoplay_videos: true
  autofocus_videos: false
  videosWidth: 960px
advanced:
  unique_token: 0
  compression_type: minified
